### ISSUE TITLE
does not work on mac

### ISSUE THREAD

**Issue by wendyliga** [nosmokingbandit/AluminumFoil#4] opened 2018-11-28 15:36 UTC
Everything works except when I want to install NSP from my MacBook

I execute the script and got this error 
```
&os.PathError{Op:"open", Path:"/path/Desktop/Hollow_Knight ", Err:0x2}
```

this is the detail terminal log
```
myMacbookName:Nintendo_Switch wendyliga$ ./AluminumFoil_Darwin
Connected to Switch
? NSP Directory: /path/Desktop/Hollow_Knight 
&os.PathError{Op:"open", Path:"/path/Desktop/Hollow_Knight ", Err:0x2}
Press Enter to exit
```

So i put the NSP Directory on non whitespace enviroment because i know the `usb_install_pc.py` from tinfoil is not work on that enviroment

I was wondering why i got this error

Thank You

**Comment by nosmokingbandit** [comment] 2019-02-25 20:00
Closing this since the project has moved on the a completely different codebase.

However, the problem is that when you drag the NSP into the terminal window it often appends a space as you can see here: `"/path/Desktop/Hollow_Knight "`. I think I eventually fixed this but I really don't remember and I'm not going back to that codebase.

**Closed by nosmokingbandit** 2019-02-25 20:00 UTC
